config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :profiles, :profile_details, :profile_links,
              :work_experiences, :skills, :educations, :services,
              :portfolios, :portfolio_photos, :testimonials

    root to: "profiles#index"
  end
  root :to => 'home#index'

  resources :portfolios, only: %i[index show], param: :slug
  resources :services, only: %i[index show], param: :slug
  resources :blog, param: :slug

  get 'about', to: 'about#index'
  get 'resume', to: 'resume#index'
  get 'contact', to: 'contact#index'
  post 'contact', to: 'contact#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'my-posts', to: 'pages#my_posts'
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'
end

app/models/service.rb
class Service < ApplicationRecord
  after_validation :set_slug, only: %i[create update]

  belongs_to :profile

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

  private

  def set_slug
    self.slug = [name.to_s.parameterize].join("-")
  end
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::ApplicationController
  # Overwrite any of the RESTful controller actions to implement custom behavior
  # For example, you may want to send an email after a foo is updated.
  #
  # def update
  #   super
  #   send_foo_updated_email(requested_resource)
  # end

  # Override this method to specify custom lookup behavior.
  # This will be used to set the resource for the `show`, `edit`, and `update`
  # actions.
  #
  # def find_resource(param)
  #   Foo.find_by!(slug: param)
  # end

  # The result of this lookup will be available as `requested_resource`

  # Override this if you have certain roles that require a subset
  # this will be used to set the records shown on the `index` action.
  #
  # def scoped_resource
  #   if current_user.super_admin?
  #     resource_class
  #   else
  #     resource_class.with_less_stuff
  #   end
  # end

  # Override `resource_params` if you want to transform the submitted
  # data before it's persisted. For example, the following would turn all
  # empty values into nil values. It uses other APIs such as `resource_class`
  # and `dashboard`:
  #
  # def resource_params
  #   params.require(resource_class.model_name.param_key).
  #     permit(dashboard.permitted_attributes).
  #     transform_values { |value| value == "" ? nil : value }
  # end

  # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
  # for more information
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[show]

  def index
    @services = current_profile.services
    @testimonials = current_profile.testimonials
  end

  def show; end

  private

  def set_service
    @service = Service.find_by(slug: params[:slug])
  end
end

app/views/services/index.html.erb
<section id="services" class="services">
  <div class="container">
    <div class="section-title">
      <h2>Services</h2>
      <p>Offers various services in IT industry to utilize and maximize my skills and capabilities with a vision to provide customer's needs and demands and a mission to achieve customer's satisfaction.</p>
    </div>

    <div class="row">
      <% @services.each do |service| %>
        <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">
          <div class="icon"><i class="bi bi-<%= service.icon.present? ? service.icon : 'gear' %>"></i></div>
          <h4 class="title"><a href="<%= service_url(service.slug) %>"><%= service.name %></a></h4>
          <p class="description"><%= service.description %></p>
        </div>
      <% end %>
  </div>
</section>

<%= render template: "testimonials/index", locals: { testimonials: @testimonials } %>

app/views/services/show.html.erb
<%= render '/shared/breadcrumbs', title: @service.name, menu: "Services", link: services_path  %>

<section class="inner-page">
  <div class="container">
    <p>
      <%= @service.description %>
    </p>
  </div>
</section>