config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :profiles, :profile_details, :profile_links,
              :work_experiences, :skills, :educations, :services,
              :portfolios, :portfolio_photos, :testimonials

    root to: "profiles#index"
  end
  root :to => 'home#index'

  resources :portfolios, only: %i[index show], param: :slug
  resources :services, only: %i[index show], param: :slug
  resources :blog, param: :slug

  get 'about', to: 'about#index'
  get 'resume', to: 'resume#index'
  get 'contact', to: 'contact#index'
  post 'contact', to: 'contact#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'my-posts', to: 'pages#my_posts'
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :profile

  validates :course, :school_name, :date_graduated, presence: true

  def date_graduated_display
    date_graduated.to_s(:long)
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  after_validation :set_slug, only: %i[create update]

  belongs_to :profile
  has_many :portfolio_photos, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :category, :project_date, presence: true
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }

  def project_date_display
    project_date.to_s(:month_and_year)
  end

  private

  def set_slug
    self.slug = [title.to_s.parameterize].join("-")
  end
end

app/models/portfolio_photo.rb
class PortfolioPhoto < ApplicationRecord
  belongs_to :portfolio

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10, maximum: 100 }
end

app/models/profile.rb
class Profile < ApplicationRecord
  # after_validation :set_home_photo, only: %i[create update]
  # after_validation :set_profile_photo, only: %i[create update]

  has_many :profile_details, dependent: :destroy
  has_many :profile_links, dependent: :destroy
  has_many :work_experiences, dependent: :destroy
  has_many :skills, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :services, dependent: :destroy
  has_many :portfolios, dependent: :destroy
  has_many :testimonials, dependent: :destroy

  validates :first_name, :last_name, presence: true

  def fullname
    "#{first_name} #{last_name}"
  end

  # private

  # def set_home_photo
  #   photo = Cloudinary::Uploader.upload(home_photo)
  #   self.home_photo = photo["url"]
  # end

  # def set_profile_photo
  #   photo = Cloudinary::Uploader.upload(profile_photo)
  #   self.profile_photo = photo["url"]
  # end
end

app/models/profile_detail.rb
class ProfileDetail < ApplicationRecord
  belongs_to :profile

  validates :title, :content, :sort_order, presence: true
end

app/models/profile_link.rb
class ProfileLink < ApplicationRecord
  belongs_to :profile

  validates :name, :url, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  after_validation :set_slug, only: %i[create update]

  belongs_to :profile

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

  private

  def set_slug
    self.slug = [name.to_s.parameterize].join("-")
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :profile

  validates :skill_name, :proficiency, presence: true
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  belongs_to :profile

  validates :customer_name, presence: true
  validates :statement, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/work_experience.rb
class WorkExperience < ApplicationRecord
  belongs_to :profile

  validates :job_title, :employer_name, :date_started, presence: true
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

  def work_period
    started = date_started.to_s(:month_and_year)
    ended = date_ended.present? ? date_ended.to_s(:month_and_year) : "Present"

    "#{started} to #{ended}"
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  include BlogHelper
  before_action :authorized, except: %i[index show]
  before_action :set_post, only: %i[show edit]
  before_action :check_cancel, only: %i[create update]

  def index
    @posts = display_posts
  end

  def show; end

  def new; end

  def create
    response = create_post(post_params)

    if response["message"].present?
      flash.now[:alert] = response
      render :new
    end

    return if response["data"].nil?

    redirect_to my_posts_path,
                flash: { notice: "You have successfully created a new post!" }
  end

  def edit; end

  def update
    response = update_post(params[:slug], post_params)

    if response["message"].present?
      flash.now[:alert] = response
      render :show
    end

    return if response["data"].nil?

    redirect_to blog_path(response["data"]["to_param"]),
                flash: { notice: "You have successfully updated this post!" }
  end

  def destroy
    response = delete_post(params[:slug])

    if response["message"].present?
      flash.now[:alert] = response
      render :show
    end

    return if response["status"].nil?

    redirect_to my_posts_path,
                flash: { notice: "You have successfully deleted your post!" }
  end

  private

  def set_post
    @post = show_post(params[:slug])
  end

  def post_params
    params[:image] = upload_photo(params[:image]) if params[:image].present?

    params.permit(:title, :image, :content)
  end

  def check_cancel
    return unless params[:commit] == "Cancel"

    return redirect_to blog_path(params[:slug]) if params[:slug].present?

    redirect_to my_posts_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
require "faraday"
require "faraday_middleware"

module ApplicationHelper
  def active?(link_path)
    current_page?(link_path) ? "active" : ""
  end

  def current_profile
    Profile.first
  end

  def cloudinary_upload(photo)
    Cloudinary::Uploader.upload(photo)
  end

  def upload_photo(photo)
    uploaded_file = cloudinary_upload(photo)

    uploaded_file["url"]
  end

  def faraday_conn
    url = ENV["BLOG_API_URL"]

    Faraday.new(url: url) do |faraday|
      faraday.adapter Faraday.default_adapter
      faraday.response :json
    end
  end

  def logged_in?
    session[:current_user].present?
  end

  def current_user
    session[:current_user]["user"] if logged_in?
  end

  def bearer_token
    session[:current_user]["token"] if logged_in?
  end

  def post_owner?(post_user)
    logged_in? && current_user["id"] == post_user["id"]
  end
end

app/helpers/blog_helper.rb
module BlogHelper
  def request_header
    {
      "Authorization" => "Bearer #{bearer_token}",
      "Content-Type"  => "application/json"
    }
  end

  def display_posts
    response = faraday_conn.get("posts")

    response.body
  end

  def show_post(slug)
    response = faraday_conn.get("posts/#{slug}")

    response.body["data"].presence
  end

  def create_post(body)
    response = faraday_conn.post("posts", body.to_json, request_header)

    response.body
  end

  def update_post(slug, body)
    response = faraday_conn.patch("posts/#{slug}", body.to_json, request_header)

    response.body
  end

  def delete_post(slug)
    response = faraday_conn.delete("posts/#{slug}", nil, request_header)

    response.body
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def user_posts
    response = faraday_conn.get("my-posts", nil,
                                "Authorization" => "Bearer #{bearer_token}")

    response.body
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def authenticate_user(body)
    response = faraday_conn.post("login", body.to_json,
                                 "Content-Type" => "application/json")

    response.body
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def register_user(body)
    response = faraday_conn.post("users", body.to_json,
                                 "Content-Type" => "application/json")

    response.body
  end
end

app/views/fields/cloudinary_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= field.thumb %>
  <%= f.file_field field.attribute %>
</div>

app/views/fields/cloudinary_field/_index.html.erb
<%= field.thumb %>

app/views/fields/cloudinary_field/_show.html.erb
<%= field.thumb %>

app/views/shared/_breadcrumbs.html.erb
<section id="breadcrumbs" class="breadcrumbs">
  <div class="container">

    <div class="d-flex justify-content-between align-items-center">
      <h2><%= title %></h2>
      <ol>
        <li><%= link_to "Home", root_path %></li>
        <% if menu.present? %>
          <li><%= link_to menu, link %></li>
        <% end %>
        <li><%= title %></li>
      </ol>
    </div>

  </div>
</section>

app/views/shared/_error_messages.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert.present? %>
  <div class="alert alert-danger" role="alert">
    <%= alert["message"] %>
    <% if alert["errors"].present? %>
      <ul>
        <% alert["errors"].values.each do |message| %>
          <li><%= message.first %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="copyright">
      &copy; Copyright 2021 <strong><span>Etnaner</span></strong> &reg;
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<!-- ======= Mobile nav toggle button ======= -->
<button type="button" class="mobile-nav-toggle d-xl-none"><i class="bi bi-list"></i></button>

<header id="header">
  <div class="d-flex flex-column">
    <%= render 'shared/profile' %>
    <%= render 'shared/nav' %>
    <button type="button" class="mobile-nav-toggle d-xl-none"><i class="bi bi-list"></i></button>
  </div>
</header>

app/views/shared/_nav.html.erb
<nav class="nav-menu">
  <ul>
    <li class="<%= active?(root_path) %>">
      <%= link_to "<i class='bi bi-house-door'></i> <span>Home</span>".html_safe, root_path %>
    </li>
    <li class="<%= active?(about_path) %>">
      <%= link_to "<i class='bi bi-person'></i> <span>About</span>".html_safe, about_path %>
    </li>
    <li class="<%= active?(resume_path) %>">
      <%= link_to "<i class='bi bi-file-earmark'></i> <span>Resume</span>".html_safe, resume_path %>
    </li>
    <li class="<%= active?(portfolios_path) %>">
      <%= link_to "<i class='bi bi-card-image'></i> <span>Portfolio</span>".html_safe, portfolios_path %>
    </li>
    <li class="<%= active?(services_path) %>">
      <%= link_to "<i class='bi bi-gear'></i> <span>Services</span>".html_safe, services_path %>
    </li>
    <li class="<%= active?(blog_index_path) %>">
      <%= link_to "<i class='bi bi-card-list'></i> <span>Blog</span>".html_safe, blog_index_path %>
    </li>
    <li class="<%= active?(contact_path) %>">
      <%= link_to "<i class='bi bi-envelope'></i> <span>Contact</span>".html_safe, contact_path %>
    </li>
  </ul>
</nav>

app/views/shared/_profile.html.erb
<div class="profile">
  <%= cl_image_tag(current_profile.profile_photo, class: "img-fluid rounded-circle") %>
  <h1 class="text-light"><%= link_to current_profile.fullname, root_path %></h1>
  <div class="social-links mt-3 text-center">
    <% current_profile.profile_links.each do |link| %>
      <a href="<%= link.url %>" target="_blank"><i class="bi bi-<%= link.icon %>"></i></a>
    <% end %>
  </div>
</div>