config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :profiles, :profile_details, :profile_links,
              :work_experiences, :skills, :educations, :services,
              :portfolios, :portfolio_photos, :testimonials

    root to: "profiles#index"
  end
  root :to => 'home#index'

  resources :portfolios, only: %i[index show], param: :slug
  resources :services, only: %i[index show], param: :slug
  resources :blog, param: :slug

  get 'about', to: 'about#index'
  get 'resume', to: 'resume#index'
  get 'contact', to: 'contact#index'
  post 'contact', to: 'contact#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'my-posts', to: 'pages#my_posts'
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  include BlogHelper
  before_action :authorized, except: %i[index show]
  before_action :set_post, only: %i[show edit]
  before_action :check_cancel, only: %i[create update]

  def index
    @posts = display_posts
  end

  def show; end

  def new; end

  def create
    response = create_post(post_params)

    if response["message"].present?
      flash.now[:alert] = response
      render :new
    end

    return if response["data"].nil?

    redirect_to my_posts_path,
                flash: { notice: "You have successfully created a new post!" }
  end

  def edit; end

  def update
    response = update_post(params[:slug], post_params)

    if response["message"].present?
      flash.now[:alert] = response
      render :show
    end

    return if response["data"].nil?

    redirect_to blog_path(response["data"]["to_param"]),
                flash: { notice: "You have successfully updated this post!" }
  end

  def destroy
    response = delete_post(params[:slug])

    if response["message"].present?
      flash.now[:alert] = response
      render :show
    end

    return if response["status"].nil?

    redirect_to my_posts_path,
                flash: { notice: "You have successfully deleted your post!" }
  end

  private

  def set_post
    @post = show_post(params[:slug])
  end

  def post_params
    params[:image] = upload_photo(params[:image]) if params[:image].present?

    params.permit(:title, :image, :content)
  end

  def check_cancel
    return unless params[:commit] == "Cancel"

    return redirect_to blog_path(params[:slug]) if params[:slug].present?

    redirect_to my_posts_path
  end
end

app/helpers/blog_helper.rb
module BlogHelper
  def request_header
    {
      "Authorization" => "Bearer #{bearer_token}",
      "Content-Type"  => "application/json"
    }
  end

  def display_posts
    response = faraday_conn.get("posts")

    response.body
  end

  def show_post(slug)
    response = faraday_conn.get("posts/#{slug}")

    response.body["data"].presence
  end

  def create_post(body)
    response = faraday_conn.post("posts", body.to_json, request_header)

    response.body
  end

  def update_post(slug, body)
    response = faraday_conn.patch("posts/#{slug}", body.to_json, request_header)

    response.body
  end

  def delete_post(slug)
    response = faraday_conn.delete("posts/#{slug}", nil, request_header)

    response.body
  end
end

app/views/blog/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Home", blog_index_path, class: "nav-link #{active?(blog_index_path)}" %>
        <% if logged_in? %>
          <%= link_to "My Posts", my_posts_path, class: "nav-link #{active?(my_posts_path)}" %>
          <%= link_to "Logout", logout_path, class: "nav-link" %>
        <% else %>
          <%= link_to "Login", login_path, class: "nav-link #{active?(login_path)}" %>
        <% end %>
      </div>
    </div>
    <% if logged_in? %>
      <div class="d-flex">
        <%= link_to "Create New Post", new_blog_path, class: "btn btn-outline-dark btn-sm" %>
      </div>
    <% end %>
  </div>
</nav>

app/views/blog/edit.html.erb
<section id="blog" class="blog">
  <div class="container">
    <div class="section-title">
      <h2>Personal Blog</h2>
      <p>Dream, Explore & Discover the Best Tech for your Best Future!</p>
    </div>

    <%= render 'blog/nav' %>

    <div class="container blog-container" data-aos="fade-in">
      <div class="row">
        <div class="post-form bg-light mt-4 p-4">
          <%= form_with url: blog_path(params[:slug]), method: :patch, class: "row g-3" do |f| %>
            <h4>Edit Post</h4>
            <div class="col-12">
              <%= f.label :title %>
              <%= f.text_field :title, class: "form-control", placeholder: "Title", value: @post["title"] %>
            </div>
            <div class="col-12">
              <%= f.label :image %>
              <%= f.file_field :image, class: "form-control" %>
              <%= cl_image_tag(@post["image"], width: 200, crop: "pad", class: "rounded mt-2") %>
            </div>
            <div class="col-12">
              <%= f.label :content %>
              <%= f.text_area :content, rows: 5, class: "form-control", placeholder: "Content", value: @post["content"] %>
            </div>
            <div class="col-12">
              <%= render "shared/error_messages" %>
              <div class="float-end">
                <%= f.submit "Update", class: "btn btn-dark btn-md" %>
                <%= f.submit "Cancel", class: "btn btn-secondary btn-md" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/blog/index.html.erb
<section id="blog" class="blog">
  <div class="container">
    <div class="section-title">
      <h2>Personal Blog</h2>
      <p>Dream, Explore & Discover the Best Tech for your Best Future!</p>
    </div>

    <%= render 'blog/nav' %>

    <div class="mt-3">
      <%= render "shared/error_messages" %>
    </div>

    <div class="container blog-container" data-aos="fade-in">
      <% if @posts["data"].count == 0 %>
        <div class="alert alert-warning" role="alert">
          No available posts!
        </div>
      <% end %>

      <% @posts["data"].each do |post| %>
        <div class="blog-item">
          <div class="card m-3">
            <div class="row g-0">
              <div class="col-md-4">
                <%= cl_image_tag(post["image"], :class => "img-fluid rounded-start") if post["image"].present? %>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title"><%= post["title"] %></h5>
                  <p class="card-text">
                    <small class="text-muted">
                      by <%= post["user"]["full_name"] %> |
                      <%= post["created_at"].to_s.to_time.strftime('%d %b %Y') %> |
                      <%= post["comments"] %>
                      <%= post["comments"] > 0 ? 'comments' : 'comment' %>
                    </small>
                  </p>
                  <p class="card-text">
                    <small><%= truncate(post["content"], length: 200) %></small>
                  </p>
                  <p class="card-text" style="text-align:right">
                    <%= link_to "Read more", blog_path(post["to_param"]), class: "btn btn-outline-success btn-sm" %>
                    <% if post_owner?(post["user"]) %>
                      <%= link_to "Edit Post", edit_blog_path(post["to_param"]), class: "btn btn-outline-secondary btn-sm" %>
                      <%= link_to "Delete Post", blog_path(post["to_param"]), class: "btn btn-outline-danger btn-sm", method: :delete %>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/blog/new.html.erb
<section id="blog" class="blog">
  <div class="container">
    <div class="section-title">
      <h2>Personal Blog</h2>
      <p>Dream, Explore & Discover the Best Tech for your Best Future!</p>
    </div>

    <%= render 'blog/nav' %>

    <div class="container blog-container" data-aos="fade-in">
      <div class="row">
        <div class="post-form bg-light mt-4 p-4">
          <%= form_with url: blog_index_path, method: :post, class: "row g-3" do |f| %>
            <h4>Create New Post</h4>
            <div class="col-12">
              <%= f.label :title %>
              <%= f.text_field :title, class: "form-control", placeholder: "Title", value: params[:title] %>
            </div>
            <div class="col-12">
              <%= f.label :image %>
              <%= f.file_field :image, class: "form-control" %>
            </div>
            <div class="col-12">
              <%= f.label :content %>
              <%= f.text_area :content, rows: 5, class: "form-control", placeholder: "Content", value: params[:content] %>
            </div>
            <div class="col-12">
              <%= render "shared/error_messages" %>
              <div class="float-end">
                <%= f.submit "Save", class: "btn btn-dark btn-md" %>
                <%= f.submit "Cancel", class: "btn btn-secondary btn-md" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/blog/show.html.erb
<%= render '/shared/breadcrumbs', title: truncate(@post["title"]), menu: "Blog", link: blog_index_path  %>

<section class="inner-page">
  <div class="container">
    <%= render "shared/error_messages" %>

    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title"><%= @post["title"] %></h5>
        <p class="card-text">
          <small><%= simple_format(@post["content"]) %></small>
        </p>
        <p class="card-text">
          <small class="text-muted">
            Posted by: <%= @post["user"]["full_name"] %> |
            <%= @post["created_at"].to_s.to_time.strftime('%d %b %Y') %> |
            <%= @post["comments"] %>
            <%= @post["comments"] > 0 ? 'comments' : 'comment' %>
          </small>
        </p>
        <% if post_owner?(@post["user"]) %>
          <p class="card-text" style="text-align:right">
            <%= link_to "Edit Post", edit_blog_path(@post["to_param"]), class: "btn btn-outline-secondary btn-sm" %>
            <%= link_to "Delete Post", blog_path(@post["to_param"]), class: "btn btn-outline-danger btn-sm", method: :delete %>
          </p>
        <% end %>
      </div>
      <%= cl_image_tag(@post["image"], :class => "card-img-bottom rounded-bottom") if @post["image"].present? %>
    </div>
  </div>
</section>